[theme]
primaryColor="#A81C47C"
backgroundColor="#CEFACA"
secondaryBackgroundColor="#DEFADC"
textColor="#20344F"
font = "DynaPuff"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
